//
// Created by User on 2026/5/4.
//

#ifndef CMAKEDIRECT3D12GAMEVCPKG_MYRENDERER_H
#define CMAKEDIRECT3D12GAMEVCPKG_MYRENDERER_H


class MyRenderer {
};


#endif //CMAKEDIRECT3D12GAMEVCPKG_MYRENDERER_H