//
// Created by User on 2026/5/7.
//

#ifndef CMAKEDIRECT3D12GAMEVCPKG_PROJECT_SETTINGS_H
#define CMAKEDIRECT3D12GAMEVCPKG_PROJECT_SETTINGS_H


class project_settings {
};


#endif //CMAKEDIRECT3D12GAMEVCPKG_PROJECT_SETTINGS_H